In [6]:
import plotly.express as px

def word_freq(df):
    word_counts = df["Word"].value_counts().reset_index()
    word_counts.columns = ["Word", "Frequency"]

    top20 = word_counts.head(20)

    fig = px.bar(
        top20,
        x="Frequency",
        y="Word",
        orientation="h",
        title="Crossword Word Frequencies",
        height=500
    )
    fig.update_layout(yaxis=dict(autorange="reversed"))

    fig.show()

def word_length_dist(df):
    df["Length"] = df["Word"].str.len()

    length_counts = df["Length"].value_counts().sort_index().reset_index()
    length_counts.columns = ["Length", "Count"]

    fig = px.bar(
        length_counts,
        x="Length",
        y="Count",
        title="Word Length Distribution in Cavalier Daily Crosswords",
        labels={"Length": "Word Length", "Count": "Number of Words"},
        height=500,
        width=900
    )

    fig.show()

def words_max_length(df):
    max_len = df["Length"].max()

    longest_words = df[df["Length"] == max_len]["Word"].value_counts().reset_index()
    longest_words.columns = ["Word", "Frequency"]

    fig = px.bar(
        longest_words,
        x="Frequency",
        y="Word",
        orientation="h",
        title=f"Longest Words in Crosswords (Length = {max_len})",
        height=500
    )

    fig.update_layout(yaxis=dict(autorange="reversed"))

    fig.show()

def letter_freq(df):

    letters = "".join(df["Word"].dropna())
    letter_df = pd.Series(list(letters)).value_counts().reset_index()
    letter_df.columns = ["Letter", "Frequency"]

    fig = px.bar(letter_df, x="Letter", y="Frequency", title="Letter Frequency in Crosswords", width = 1000)

    fig.show()
    return letter_df

In [11]:
import pandas as pd
import plotly.express as px

big_df = pd.read_csv("bigs.csv")

word_length_dist(big_df)

word_freq(big_df)

words_max_length(big_df)

ld = letter_freq(big_df)

print(ld.loc[ld["Frequency"]>2000])

big_df.loc[big_df["Length"]==15]

  Letter  Frequency
0      E       4542
1      A       4208
2      S       3184
3      O       2646
4      R       2544
5      T       2374
6      I       2182
7      N       2125

      Unnamed: 0        Date             Word  Length
469          469  2026-02-04  RUPAULSDRAGRACE    15.0
491          491  2026-02-04  MISTERPRESIDENT    15.0
712          712  2026-01-29  TASTETHERAINBOW    15.0
1858        1858  2025-11-25  FATHERCHRISTMAS    15.0
1882        1882  2025-11-25  LITTLESAINTNICK    15.0
4038        4038  2025-06-12  PLAYGROUNDSLIDE    15.0
4075        4075  2025-06-12  THREECOURSEMEAL    15.0
5603        5603  2025-02-18  CORPORATEJARGON    15.0
5611        5611  2025-02-18  CHICAGOWHITESOX    15.0
6602        6602  2024-11-23  QUITSCOLDTURKEY    15.0
6623        6623  2024-11-23  THANKSGIVINGDAY    15.0
6767        6767  2024-11-10  SEVENDEADLYSINS    15.0
6925        6925  2024-10-18  AROUNDTHECORNER    15.0

In [12]:
mini_df = pd.read_csv("minis.csv")

word_length_dist(mini_df)

word_freq(mini_df)

words_max_length(mini_df)
ld = letter_freq(mini_df)

print(ld.loc[ld["Frequency"]<100])
mini_df.loc[mini_df["Length"]>5]

   Letter  Frequency
17      G         82
18      K         58
19      V         54
20      W         44
21      F         38
22      J         28
23      X         14
24      Q          8
25      Z          6
26      7          2

      Unnamed: 0        Date       Word  Length
1170        1210  2025-09-18  FIRSTDOWN       9
1177        1217  2025-09-18   DEADLAST       8
1178        1218  2025-09-18   FIRSTAID       8
1179        1219  2025-09-18     DEVOID       6
1184        1224  2025-09-18     NEARED       6
1185        1225  2025-09-18    OUTLAST       7