In [55]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import json
from datetime import datetime
import pandas as pd
import time

In [87]:
def grid_parser(driver, url):
    driver.get(url)
    time.sleep(1)

    rows = []
    iframes = driver.find_elements(By.CSS_SELECTOR, "iframe[src*='crosshare']")

    for idx in range(len(iframes)):
        try:
            iframes = driver.find_elements(By.CSS_SELECTOR, "iframe[src*='crosshare']")
            if idx >= len(iframes):
                break

            iframe = iframes[idx]
            src = iframe.get_attribute("src")
            print("src:", src)
            if not src or "crosshare" not in src:
                continue

            driver.switch_to.frame(iframe)
            print("a")
            time.sleep(0.5)

            script = driver.find_element(By.ID, "__NEXT_DATA__")
            json_text = script.get_attribute("innerHTML")

            data = json.loads(json_text)
            puzzle = data["props"]["pageProps"]["puzzle"]
            grid = puzzle["grid"]
            cols = puzzle["size"]["cols"]
            t = puzzle["publishTime"]
            dt = datetime.fromtimestamp(t / 1000).date()

            words = []

            # across words
            for i in range(0, len(grid), cols):
                row = grid[i:i + cols]
                row_str = "".join(row)
                for word in row_str.split("."):
                    if len(word) >= 2:
                        words.append(word)

            # down words
            for c in range(cols):
                col_chars = []
                for r in range(0, len(grid), cols):
                    col_chars.append(grid[r + c])

                col_str = "".join(col_chars)
                for word in col_str.split("."):
                    if len(word) >= 2:
                        words.append(word)

            for w in words:
                rows.append({"Date": dt, "Word": w})

        except Exception as e:
            print("iframe error:", url, idx, e)

        finally:
            try:
                driver.switch_to.default_content()
            except:
                pass

    return pd.DataFrame(rows)

In [57]:
def retrieveArticles(page, page_size):
    baseurl = f"https://www.cavalierdaily.com/section/quizzes?page={page}&per_page={page_size}"
    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(baseurl, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    links = []
    for a in soup.find_all("a", href = True):
        href = a["href"] 
        if "mini-crosswords" in href.lower():
            if href not in links:
                links.append(href)
    return links

In [83]:
df = (grid_parser(url = "https://www.cavalierdaily.com/article/2026/01/crossword-january-1?ct=content_open&cv=cbox_latest"))

src: https://crosshare.org/embed/iHLG0XdvB5J6mY7vcHmf/WiiyxL2cINd3FR9tuwaK94IvgsI2
a

In [84]:
df

          Date    Word
0   2025-12-26    CLUB
1   2025-12-26     NAB
2   2025-12-26   MAGMA
3   2025-12-26    HOBO
4   2025-12-26    POUR
..         ...     ...
75  2025-12-26  EGRESS
76  2025-12-26    ARMY
77  2025-12-26     ATM
78  2025-12-26   ASTRO
79  2025-12-26    RAYS

[80 rows x 2 columns]

In [88]:
df = pd.DataFrame()
links = retrieveArticles(1, 200)
print(links)

options = Options()
options.page_load_strategy = "eager"
driver = webdriver.Chrome(options=options)

try:
    for i, l in enumerate(links):
        if i > 0 and i % 25 == 0:
            driver.quit()
            driver = webdriver.Chrome(options=options)
            print("restarted browser")

        print("link", l)
        try:
            articledf = grid_parser(driver, l)
            df = pd.concat([df, articledf], ignore_index=True)
        except Exception as e:
            print("failed on", l, e)
finally:
    driver.quit()

['https://www.cavalierdaily.com/article/2026/03/mini-crosswords-week-of-3-9?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/03/mini-crosswords-week-of-3-2?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-23?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-16?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-9?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-2?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-26?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-19?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-12?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-5?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2026/01/mini-crosswords-jan-1-and-jan-2?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-22?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-15?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-8?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-1?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-24?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-weekend-of-nov-22?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-17?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-10?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-weekend-of-nov-8?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-3?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-27?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-20?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-13-68f18a0113b9d?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-13?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-6-a?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-sept-29?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-22?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-15?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-8-68be342d27b30?ct=content_open&cv=cbox_latest', 'https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-1-68b4ca198fa1a?ct=content_open&cv=cbox_latest']
link https://www.cavalierdaily.com/article/2026/03/mini-crosswords-week-of-3-9?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/G6Pnxeg100AfT5LH1r5t/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/OqDwmtAvH0FiirO6HNjM/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/OHGg6pjFn0BQjr7mEo4H/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/r7jbab1161dtnXBEwlkR/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/03/mini-crosswords-week-of-3-2?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/DcMAUtizptujcRE5ROpk/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/p4m5Yu2EFxkVlLrftkZ3/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/NJgzQ6nYnVlGvTNV6xov/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-23?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/q5tZFBshSMbTvWFNwt7I/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/d3F2iDHtUM85SA2DFMrv/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/gV1ZPra9Q3HVNYem9fww/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/L1S6XX8iNFlXpbOe2gIn/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/RcOKqLE5i6qn1ZDH2OvL/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-16?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/BcyvNqckeCVhibSK4LZx/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/3I8FCCzbXDvTAZGhKqKH/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/oMlZFnC3r0txQ4e8NURP/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/mL6g9rcQTuEQRO5akcYz/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/F9rF5ROeVz5yzs0E82PW/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-9?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/eayL4xA9VqPP24nb0kiw/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/aLX1KjmrjxKwTasfe0Us/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/ePiXJbrtqQsyPzEUF1qH/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/qDBpGgf4Vb4VdKPiu1QB/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/tbJe84cR2nkumhzMvAcX/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/02/mini-crosswords-week-of-feb-2?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/SHsFui0LozNiRfGzV2ow/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/t9Uzu1XlYzd8C5j4ePSi/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/PPQ6wUOgGliPNmOFvxy5/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/gu6upWFaQkkRtlpXYmjK/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/bJhLXml80sF43CuyMrGr/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-26?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/whiExPjfb35LwI22TDbE/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/11Pj8MS11uZHdnXJU2EP/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/1HZDJJUP08CIc33MCR1G/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/ArR4QHpeNHOp4GVUT0c1/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/VtY0eMYaFOlPTVepmtmA/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-19?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/hfDoGM6lQqdBj46KQMom/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/kgGJVDHYh76yWtN5bWee/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/Cjj6tffhsWU0ws1TcTSW/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
src: https://crosshare.org/embed/oGw5Kaguiamynvpmo9b9/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/LaJ7CYmawacUmzPjrkOH/A0UAlkGn4kOUHLzUm2dfHNZOoLP2
a
link https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-12?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/VpFEscVbcZRloufgIelt/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/fXe5B4paMVUqfNxjbZhg/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/flPZUDs8W2SCn5HLMY7M/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/EJ3SoJ70jHTX3F2JMkJg/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/ADmDL1aHrsw47Zugr85h/zbEdR1uIM2bRvberfp1hARkIlhz2
a
link https://www.cavalierdaily.com/article/2026/01/mini-crosswords-week-of-jan-5?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/rQdbxDtgxEuqUmfsoFh0/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/09wyjq0pcEHZerQIZ1cP/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/S5cefQgDdjACgL2oZ5LL/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/Zshg2Qm3l1arfqmwSAAx/zbEdR1uIM2bRvberfp1hARkIlhz2
a
src: https://crosshare.org/embed/Tof2556ZQhnwE3qCvJL8/zbEdR1uIM2bRvberfp1hARkIlhz2
a
link https://www.cavalierdaily.com/article/2026/01/mini-crosswords-jan-1-and-jan-2?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/NDAhhWiLUTlw9XbrXbsq/9NCwSKd6UBXyk2WqG3LjXm8ogoq1
a
src: https://crosshare.org/embed/EYiEXXpboVji4XMpiK8O/9NCwSKd6UBXyk2WqG3LjXm8ogoq1
a
link https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-22?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/gdPDRWXO5CcmhH5dP52s/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/wGoOv0HpVJxnVHzaukee/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/cFaWzI9sOLcbooKMKZo4/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/fN9o1vUiWsTRwWGASHxy/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/wiKTj4dYHJXyPqelddaT/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-15?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/4OBv323eS0x4Aa6hDx3L/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-8?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/wEoripCGeSbLTDm9zuVk/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ri3C7NHyaGEPZ4LwYwtt/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/2fCYYTwNFge127TBW0L8/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/PnRTajvQHOQWZOXVcClI/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/QwDUEYWNOUqYbKB7YSBa/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/12/mini-crosswords-week-of-dec-1?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/RPCj5JNbr5uXu0dp6ocf/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/3bNF36x1OjhQzg8nYxjQ/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/1VzTmEnbpcIIRt3a7uN5/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/DXO7syRl7kfCtozSszy3/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/Jg8r9eRRZF0ch8iQTeGP/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-24?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/vsDca0SznGGkOIG27dCO/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/Tn1rRK83QJtS1Vpggcaj/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/SXBaFQLsQAl2p6qzlwyb/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/HAE7XwG827pkqSrgxsIN/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ILMSp9gIx64h6R87RR5L/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-weekend-of-nov-22?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/ucFoO5cVvlETYfCB9BcL/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/mDOTRCTX0fOyLr6qMRpB/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-17?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/jbduSn17DlUafESZY5yP/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/zVKe83mu5vzEN3nmh8cu/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ssbfbhDPFM3F2TCuDvHM/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/XN6Tm24X5bz49aAy2Esb/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-10?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/oZY9nxc6w1E7P6Ye3AW5/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/NdclgtxseR5tzb6TDzJs/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/IVvrSwSX6BdNCMVq7XRN/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ZDAo4fwiBNHlJiUN7Adc/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/jPau1kSbsflCe6YoHARA/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-weekend-of-nov-8?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/6Y6amOMq1vXIGerRFL4f/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/HXdgEkxDjdWYwp2T9VTt/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/11/mini-crosswords-week-of-nov-3?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/Z9AHr4TTLUhgiovFhlCA/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/mlKcc664WIRNjmcx1qGC/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/TiRZXBh8Z8s8nirzm8hn/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/syeRnK5SKWZU9h87XbQf/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/fKTQhFu2O8PWabolnuq3/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-27?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/BsKMUcGs4vmt3QHwtb6s/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/Ixn9BNTC3W00ek9Wjvzm/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/RmE3LWiGh85kWOMVaYMs/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/KqTeEE2pcVnyfqqqwOTh/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/CxQGWOjGR4E0ePjNS4OO/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-20?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/nzMfAvYH3MKkHwgZWk4i/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/UUZOhopsQ32ZPu7NwJzX/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/IJsSSkaX8UCufl0yN7tg/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/W783XLhQr2V06GIlRp7C/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/6c9w8LGNXxwFJqCJcVp0/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-13-68f18a0113b9d?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/k6Q0pcl46UkdWdaDR7GP/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ONgIpcBIFhgazVVbA0ZS/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/lT3ecZEb0mzPIOqK0dmE/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/15vnoTu0DfaBhhZvIobA/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/3Za8Vs1T4ldsU6VLw9l7/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-13?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/ONgIpcBIFhgazVVbA0ZS/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/lT3ecZEb0mzPIOqK0dmE/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/15vnoTu0DfaBhhZvIobA/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/3Za8Vs1T4ldsU6VLw9l7/RoqCuA34iOXXQFFlmirurEWMRgA3
a
restarted browser
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-oct-6-a?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/OIdO3mCqZ9w462vVL7qX/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/leDFofYeT6smfwebXDt7/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/0WzwdxIw8XQpI2Cf2mYG/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/n4sCkoklqxyuhAcISgDt/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/sySIUvyP8hu2RZvJorn9/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/10/mini-crosswords-week-of-sept-29?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/4vSnNVuFHuOY898pfkNf/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/N7gsLywpmMSZdMO8B2LV/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/ZNk8EOO2AidDPKb4VJxE/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/XVFhMZQYe5LjmjKhWI6M/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/q5eRuEGJR9mAEyXtznGl/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-22?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/6qy48sKRiBznm3iDSBid/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/NYqU7m0gMebGQHLsC13u/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/HFBbwrXztVkdLZjImFSK/RoqsCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/osmXd1N4K5lWZmtJXF5n/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-15?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/hu8pWjLeiRbMMmOyD5v8/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/SLuML6q6jkuKfXLEB3dn/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/bUnYAITJ5uF3iTTD9y8D/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/jO0eVI60o5W1YenHJETH/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/fDVKOD3pvJJjMQOd1pkS/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-8-68be342d27b30?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/JFu9L033B6BYXz1bGtFo/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/co8sY3F15oUUlJk0NPNs/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/HYqa2pgQRAVjIzyylPyW/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/0GwFg1dtYfRMk673jmfs/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/kmUXLETQ6HVI8gRUhKxx/RoqCuA34iOXXQFFlmirurEWMRgA3
a
link https://www.cavalierdaily.com/article/2025/09/mini-crosswords-week-of-sept-1-68b4ca198fa1a?ct=content_open&cv=cbox_latest
src: https://crosshare.org/embed/4ACMn7mI3KC2FR6otlfE/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/krtmyhUJ0qKWZHn0E2OS/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/WLKfw5SGzpaOvY3NYJjZ/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/5t84KMwOfKwkYPUdBbqx/RoqCuA34iOXXQFFlmirurEWMRgA3
a
src: https://crosshare.org/embed/KJQobWHp2WaKIDBM3wdi/RoqCuA34iOXXQFFlmirurEWMRgA3
a

In [68]:
df["Word"].value_counts().head(20)

Word
SSS      4
YESES    3
LLAMA    3
ATARI    3
SANTA    3
NOCAP    3
NAIVE    3
SPASM    2
OLIOS    2
FILMS    2
FARES    2
FLOW     2
HAY      2
OFFOF    2
NIALL    2
ELRIO    2
ONE      2
ATHOS    2
CORN     2
MEOW     2
Name: count, dtype: int64

In [91]:
most_frequent_value = df['Word'].value_counts().idxmax()

In [90]:
df.shape

(1368, 2)

In [92]:
most_frequent_value
#deal with duplicates
#

'SSS'

In [101]:
df.loc[df["Word"]=="SANTA"]

           Date   Word
508  2025-12-22  SANTA
516  2025-12-22  SANTA
561  2025-12-07  SANTA

In [99]:
df["Word"].value_counts().head(20)

Word
OLIVE    3
ATARI    3
NAIVE    3
SANTA    3
SST      2
ONEAL    2
YSL      2
INANE    2
RICE     2
ALES     2
NURSE    2
MAN      2
ANGEL    2
DENIM    2
TESS     2
SCOTT    2
STEAL    2
PLAIN    2
CIDER    2
EVIAN    2
Name: count, dtype: int64

In [80]:
df.to_csv("words.csv")

In [98]:
words_to_remove = ["WXTJ", "MARIA", "ANARM", "STYES", "SSS", "MAS", "WANTS", "XRAYS", "TIRES", "JAMS",
                   "NELLY", "OLLIE", "CLANS", "AIMEE", "PEARS", "NOCAP", "ELLIE", "LLAMA", "LINER", "YESES",
                   "SPA", "PATCH", "OCHOA", "STORY", "ASSN", "SPOSA", "PACTS", "ATHOS", "CORN", "HAY",
                   "ONE", "FILMS", "FARES", "OLIOS", "FLOW", "OFFOF", "NIALL", "ELRIO", "MEOW", "SSS"]

for w in words_to_remove:
    idx = df.index[df["Word"] == w]
    if len(idx) > 0:
        df = df.drop(idx[0])